"""
Pre-built fund composition database for popular Canadian mutual funds and ETFs.

Each entry maps a fund code or ticker to its approximate underlying allocation.
Allocations are expressed as percentages that sum to ~100.

Sources: fund fact sheets (publicly available). These are approximate and may
drift as fund managers rebalance. Users can override per-holding via
allocation_json.
"""

FUND_DATABASE: dict[str, dict] = {
    # ─── Fidelity Canada Mutual Funds ─────────────────────────────────
    "FID500": {
        "name": "Fidelity Global Fund",
        "category": "Global Equity",
        "mer": 2.14,
        "allocation": {
            "us_equity": 58,
            "intl_developed_equity": 24,
            "emerging_equity": 8,
            "cad_equity": 5,
            "cash": 5,
        },
        "top_sectors": {
            "technology": 28,
            "healthcare": 16,
            "financials": 12,
            "consumer_discretionary": 11,
            "industrials": 10,
            "communication": 7,
            "other": 16,
        },
    },
    "FID501": {
        "name": "Fidelity Global Fund Series F",
        "category": "Global Equity",
        "mer": 1.05,
        "allocation": {
            "us_equity": 58,
            "intl_developed_equity": 24,
            "emerging_equity": 8,
            "cad_equity": 5,
            "cash": 5,
        },
        "top_sectors": {
            "technology": 28,
            "healthcare": 16,
            "financials": 12,
            "consumer_discretionary": 11,
            "industrials": 10,
            "communication": 7,
            "other": 16,
        },
    },
    "FID006": {
        "name": "Fidelity Canadian Growth Company",
        "category": "Canadian Equity",
        "mer": 2.28,
        "allocation": {
            "cad_equity": 82,
            "us_equity": 12,
            "cash": 6,
        },
        "top_sectors": {
            "technology": 22,
            "industrials": 18,
            "consumer_discretionary": 15,
            "energy": 12,
            "financials": 10,
            "materials": 8,
            "other": 15,
        },
    },
    "FID585": {
        "name": "Fidelity NorthStar Fund",
        "category": "Global Equity",
        "mer": 2.19,
        "allocation": {
            "us_equity": 48,
            "cad_equity": 18,
            "intl_developed_equity": 20,
            "emerging_equity": 8,
            "cash": 6,
        },
        "top_sectors": {
            "technology": 24,
            "financials": 15,
            "healthcare": 12,
            "industrials": 11,
            "consumer_discretionary": 10,
            "energy": 8,
            "other": 20,
        },
    },
    "FID586": {
        "name": "Fidelity NorthStar Fund Series F",
        "category": "Global Equity",
        "mer": 1.10,
        "allocation": {
            "us_equity": 48,
            "cad_equity": 18,
            "intl_developed_equity": 20,
            "emerging_equity": 8,
            "cash": 6,
        },
        "top_sectors": {
            "technology": 24,
            "financials": 15,
            "healthcare": 12,
            "industrials": 11,
            "consumer_discretionary": 10,
            "energy": 8,
            "other": 20,
        },
    },
    "FID015": {
        "name": "Fidelity Canadian Balanced Fund",
        "category": "Canadian Balanced",
        "mer": 2.10,
        "allocation": {
            "cad_equity": 35,
            "cad_bonds": 30,
            "us_equity": 15,
            "intl_developed_equity": 8,
            "cash": 7,
            "global_bonds": 5,
        },
        "top_sectors": {
            "financials": 18,
            "government_bonds": 15,
            "corporate_bonds": 12,
            "energy": 10,
            "technology": 9,
            "industrials": 8,
            "other": 28,
        },
    },
    "FID016": {
        "name": "Fidelity Monthly Income Fund",
        "category": "Canadian Fixed Income Balanced",
        "mer": 1.73,
        "allocation": {
            "cad_bonds": 38,
            "cad_equity": 28,
            "us_equity": 12,
            "global_bonds": 10,
            "intl_developed_equity": 5,
            "cash": 7,
        },
        "top_sectors": {
            "government_bonds": 20,
            "corporate_bonds": 18,
            "financials": 15,
            "energy": 8,
            "utilities": 7,
            "real_estate": 5,
            "other": 27,
        },
    },
    "FID120": {
        "name": "Fidelity American Disciplined Equity Fund",
        "category": "US Equity",
        "mer": 2.23,
        "allocation": {
            "us_equity": 94,
            "cash": 6,
        },
        "top_sectors": {
            "technology": 30,
            "healthcare": 14,
            "financials": 13,
            "consumer_discretionary": 11,
            "industrials": 10,
            "communication": 8,
            "other": 14,
        },
    },
    "FID080": {
        "name": "Fidelity International Growth Fund",
        "category": "International Equity",
        "mer": 2.30,
        "allocation": {
            "intl_developed_equity": 72,
            "emerging_equity": 18,
            "cash": 5,
            "us_equity": 5,
        },
        "top_sectors": {
            "technology": 20,
            "financials": 16,
            "healthcare": 14,
            "industrials": 13,
            "consumer_discretionary": 12,
            "consumer_staples": 8,
            "other": 17,
        },
    },
    "FID090": {
        "name": "Fidelity Emerging Markets Fund",
        "category": "Emerging Markets Equity",
        "mer": 2.45,
        "allocation": {
            "emerging_equity": 90,
            "intl_developed_equity": 5,
            "cash": 5,
        },
        "top_sectors": {
            "technology": 28,
            "financials": 20,
            "consumer_discretionary": 15,
            "communication": 10,
            "materials": 8,
            "energy": 5,
            "other": 14,
        },
    },
    "FID010": {
        "name": "Fidelity Canadian Bond Fund",
        "category": "Canadian Fixed Income",
        "mer": 1.43,
        "allocation": {
            "cad_bonds": 88,
            "global_bonds": 5,
            "cash": 7,
        },
        "top_sectors": {
            "government_bonds": 45,
            "corporate_bonds": 35,
            "mortgage_backed": 8,
            "other": 12,
        },
    },
    "FID532": {
        "name": "Fidelity Global Asset Allocation Fund",
        "category": "Global Balanced",
        "mer": 2.18,
        "allocation": {
            "us_equity": 30,
            "intl_developed_equity": 15,
            "cad_equity": 10,
            "emerging_equity": 5,
            "cad_bonds": 15,
            "global_bonds": 15,
            "cash": 10,
        },
        "top_sectors": {
            "government_bonds": 16,
            "technology": 14,
            "corporate_bonds": 12,
            "financials": 10,
            "healthcare": 8,
            "industrials": 7,
            "other": 33,
        },
    },
    "FID2023": {
        "name": "Fidelity Global Innovators Fund",
        "category": "Global Equity",
        "mer": 2.32,
        "allocation": {
            "us_equity": 65,
            "intl_developed_equity": 18,
            "emerging_equity": 10,
            "cash": 7,
        },
        "top_sectors": {
            "technology": 45,
            "healthcare": 15,
            "consumer_discretionary": 12,
            "communication": 10,
            "industrials": 8,
            "other": 10,
        },
    },
    "FID305": {
        "name": "Fidelity Special Situations Fund",
        "category": "Global Equity",
        "mer": 2.28,
        "allocation": {
            "us_equity": 52,
            "intl_developed_equity": 22,
            "emerging_equity": 12,
            "cad_equity": 8,
            "cash": 6,
        },
        "top_sectors": {
            "technology": 22,
            "industrials": 15,
            "healthcare": 13,
            "financials": 12,
            "consumer_discretionary": 11,
            "materials": 8,
            "other": 19,
        },
    },
    "FID640": {
        "name": "Fidelity Canadian Large Cap Fund",
        "category": "Canadian Equity",
        "mer": 2.13,
        "allocation": {
            "cad_equity": 90,
            "us_equity": 5,
            "cash": 5,
        },
        "top_sectors": {
            "financials": 32,
            "energy": 18,
            "materials": 12,
            "industrials": 10,
            "technology": 8,
            "utilities": 5,
            "other": 15,
        },
    },

    # ─── Fidelity All-in-One ETFs ─────────────────────────────────────
    "FBAL": {
        "name": "Fidelity All-in-One Balanced ETF",
        "category": "Global Balanced ETF",
        "mer": 0.39,
        "allocation": {
            "us_equity": 20,
            "cad_equity": 15,
            "intl_developed_equity": 10,
            "emerging_equity": 5,
            "cad_bonds": 30,
            "global_bonds": 15,
            "cash": 5,
        },
        "top_sectors": {
            "government_bonds": 22,
            "corporate_bonds": 18,
            "technology": 10,
            "financials": 12,
            "other": 38,
        },
    },
    "FGRO": {
        "name": "Fidelity All-in-One Growth ETF",
        "category": "Global Growth ETF",
        "mer": 0.39,
        "allocation": {
            "us_equity": 32,
            "cad_equity": 20,
            "intl_developed_equity": 15,
            "emerging_equity": 8,
            "cad_bonds": 12,
            "global_bonds": 8,
            "cash": 5,
        },
        "top_sectors": {
            "technology": 16,
            "financials": 14,
            "government_bonds": 10,
            "industrials": 8,
            "healthcare": 7,
            "other": 45,
        },
    },
    "FEQT": {
        "name": "Fidelity All-in-One Equity ETF",
        "category": "Global Equity ETF",
        "mer": 0.37,
        "allocation": {
            "us_equity": 42,
            "cad_equity": 25,
            "intl_developed_equity": 18,
            "emerging_equity": 10,
            "cash": 5,
        },
        "top_sectors": {
            "technology": 22,
            "financials": 16,
            "industrials": 10,
            "healthcare": 9,
            "consumer_discretionary": 8,
            "energy": 7,
            "other": 28,
        },
    },

    # ─── Popular Canadian ETFs (non-Fidelity) ─────────────────────────
    "VFV": {
        "name": "Vanguard S&P 500 Index ETF",
        "category": "US Equity ETF",
        "mer": 0.09,
        "allocation": {"us_equity": 100},
        "top_sectors": {"technology": 32, "healthcare": 12, "financials": 12, "consumer_discretionary": 10, "communication": 9, "industrials": 8, "other": 17},
    },
    "XIC": {
        "name": "iShares Core S&P/TSX Capped Composite",
        "category": "Canadian Equity ETF",
        "mer": 0.06,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 32, "energy": 17, "materials": 11, "industrials": 10, "technology": 8, "other": 22},
    },
    "XUU": {
        "name": "iShares Core S&P U.S. Total Market",
        "category": "US Equity ETF",
        "mer": 0.07,
        "allocation": {"us_equity": 100},
        "top_sectors": {"technology": 30, "healthcare": 12, "financials": 12, "consumer_discretionary": 11, "industrials": 9, "other": 26},
    },
    "XEF": {
        "name": "iShares Core MSCI EAFE IMI",
        "category": "International Equity ETF",
        "mer": 0.22,
        "allocation": {"intl_developed_equity": 100},
        "top_sectors": {"financials": 18, "industrials": 15, "healthcare": 12, "consumer_discretionary": 11, "technology": 10, "other": 34},
    },
    "XEC": {
        "name": "iShares Core MSCI Emerging Markets",
        "category": "Emerging Markets ETF",
        "mer": 0.27,
        "allocation": {"emerging_equity": 100},
        "top_sectors": {"technology": 22, "financials": 20, "consumer_discretionary": 14, "communication": 10, "materials": 8, "other": 26},
    },
    "XBB": {
        "name": "iShares Core Canadian Universe Bond",
        "category": "Canadian Bond ETF",
        "mer": 0.10,
        "allocation": {"cad_bonds": 100},
        "top_sectors": {"government_bonds": 55, "corporate_bonds": 35, "mortgage_backed": 10},
    },
    "XEQT": {
        "name": "iShares Core Equity ETF Portfolio",
        "category": "Global Equity ETF",
        "mer": 0.20,
        "allocation": {"us_equity": 45, "cad_equity": 25, "intl_developed_equity": 22, "emerging_equity": 8},
        "top_sectors": {"technology": 24, "financials": 16, "industrials": 10, "healthcare": 9, "consumer_discretionary": 8, "other": 33},
    },
    "XGRO": {
        "name": "iShares Core Growth ETF Portfolio",
        "category": "Global Growth ETF",
        "mer": 0.20,
        "allocation": {"us_equity": 36, "cad_equity": 20, "intl_developed_equity": 17, "emerging_equity": 7, "cad_bonds": 12, "global_bonds": 8},
        "top_sectors": {"technology": 18, "financials": 15, "government_bonds": 10, "industrials": 8, "other": 49},
    },
    "VGRO": {
        "name": "Vanguard Growth ETF Portfolio",
        "category": "Global Growth ETF",
        "mer": 0.24,
        "allocation": {"us_equity": 33, "cad_equity": 18, "intl_developed_equity": 16, "emerging_equity": 6, "cad_bonds": 14, "global_bonds": 8, "us_bonds": 5},
        "top_sectors": {"technology": 16, "financials": 14, "government_bonds": 12, "industrials": 8, "other": 50},
    },
    "VEQT": {
        "name": "Vanguard All-Equity ETF Portfolio",
        "category": "Global Equity ETF",
        "mer": 0.24,
        "allocation": {"us_equity": 42, "cad_equity": 24, "intl_developed_equity": 22, "emerging_equity": 7, "cash": 5},
        "top_sectors": {"technology": 22, "financials": 16, "industrials": 10, "healthcare": 9, "other": 43},
    },
    "ZAG": {
        "name": "BMO Aggregate Bond Index ETF",
        "category": "Canadian Bond ETF",
        "mer": 0.09,
        "allocation": {"cad_bonds": 100},
        "top_sectors": {"government_bonds": 55, "corporate_bonds": 35, "mortgage_backed": 10},
    },
    "VAB": {
        "name": "Vanguard Canadian Aggregate Bond",
        "category": "Canadian Bond ETF",
        "mer": 0.09,
        "allocation": {"cad_bonds": 100},
        "top_sectors": {"government_bonds": 55, "corporate_bonds": 35, "mortgage_backed": 10},
    },
    "TDB902": {
        "name": "TD Canadian Index Fund",
        "category": "Canadian Equity",
        "mer": 0.33,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 33, "energy": 17, "materials": 11, "industrials": 10, "technology": 8, "other": 21},
    },
    "TDB911": {
        "name": "TD U.S. Index Fund",
        "category": "US Equity",
        "mer": 0.35,
        "allocation": {"us_equity": 100},
        "top_sectors": {"technology": 31, "healthcare": 12, "financials": 12, "consumer_discretionary": 10, "other": 35},
    },
    "TDB900": {
        "name": "TD Canadian Bond Index Fund",
        "category": "Canadian Fixed Income",
        "mer": 0.48,
        "allocation": {"cad_bonds": 100},
        "top_sectors": {"government_bonds": 55, "corporate_bonds": 35, "other": 10},
    },

    # ─── More Fidelity Canada ────────────────────────────────────────
    "FID200": {
        "name": "Fidelity True North Fund",
        "category": "Canadian Equity",
        "mer": 2.14,
        "allocation": {"cad_equity": 75, "us_equity": 15, "intl_developed_equity": 5, "cash": 5},
        "top_sectors": {"financials": 25, "energy": 15, "industrials": 14, "technology": 12, "materials": 10, "consumer_discretionary": 8, "other": 16},
    },
    "FID215": {
        "name": "Fidelity Dividend Fund",
        "category": "Canadian Dividend",
        "mer": 2.05,
        "allocation": {"cad_equity": 60, "us_equity": 25, "intl_developed_equity": 8, "cash": 7},
        "top_sectors": {"financials": 30, "energy": 15, "utilities": 10, "communication": 8, "industrials": 8, "real_estate": 6, "other": 23},
    },
    "FID230": {
        "name": "Fidelity Canadian Opportunities Fund",
        "category": "Canadian Small/Mid Cap",
        "mer": 2.32,
        "allocation": {"cad_equity": 88, "us_equity": 6, "cash": 6},
        "top_sectors": {"industrials": 22, "technology": 18, "consumer_discretionary": 14, "energy": 12, "materials": 10, "healthcare": 8, "other": 16},
    },
    "FID330": {
        "name": "Fidelity Global Dividend Fund",
        "category": "Global Dividend",
        "mer": 2.18,
        "allocation": {"us_equity": 45, "intl_developed_equity": 30, "cad_equity": 10, "emerging_equity": 8, "cash": 7},
        "top_sectors": {"financials": 22, "healthcare": 14, "consumer_staples": 12, "industrials": 10, "energy": 8, "utilities": 7, "other": 27},
    },
    "FID350": {
        "name": "Fidelity American Equity Fund",
        "category": "US Equity",
        "mer": 2.20,
        "allocation": {"us_equity": 92, "cash": 8},
        "top_sectors": {"technology": 32, "healthcare": 14, "consumer_discretionary": 12, "financials": 11, "communication": 9, "industrials": 8, "other": 14},
    },
    "FID560": {
        "name": "Fidelity Global Concentrated Equity Fund",
        "category": "Global Equity",
        "mer": 2.25,
        "allocation": {"us_equity": 55, "intl_developed_equity": 25, "emerging_equity": 10, "cash": 10},
        "top_sectors": {"technology": 30, "healthcare": 15, "consumer_discretionary": 13, "financials": 10, "industrials": 9, "other": 23},
    },
    "FID622": {
        "name": "Fidelity Insights Fund",
        "category": "US Equity",
        "mer": 2.30,
        "allocation": {"us_equity": 90, "intl_developed_equity": 5, "cash": 5},
        "top_sectors": {"technology": 35, "healthcare": 15, "consumer_discretionary": 12, "financials": 10, "communication": 8, "other": 20},
    },
    "FID050": {
        "name": "Fidelity Canadian Short Term Bond Fund",
        "category": "Canadian Short Term Bond",
        "mer": 1.18,
        "allocation": {"cad_bonds": 92, "cash": 8},
        "top_sectors": {"government_bonds": 40, "corporate_bonds": 42, "mortgage_backed": 10, "other": 8},
    },
    "FID580": {
        "name": "Fidelity Global Bond Fund",
        "category": "Global Fixed Income",
        "mer": 1.55,
        "allocation": {"global_bonds": 50, "us_bonds": 25, "cad_bonds": 15, "cash": 10},
        "top_sectors": {"government_bonds": 45, "corporate_bonds": 30, "mortgage_backed": 10, "other": 15},
    },
    "FID670": {
        "name": "Fidelity Tactical High Income Fund",
        "category": "High Yield",
        "mer": 1.85,
        "allocation": {"us_bonds": 35, "global_bonds": 25, "us_equity": 15, "cad_bonds": 15, "cash": 10},
        "top_sectors": {"corporate_bonds": 40, "government_bonds": 20, "energy": 8, "financials": 8, "other": 24},
    },
    "FCNS": {
        "name": "Fidelity All-in-One Conservative ETF",
        "category": "Global Conservative ETF",
        "mer": 0.39,
        "allocation": {"cad_bonds": 40, "global_bonds": 20, "us_equity": 12, "cad_equity": 10, "intl_developed_equity": 6, "emerging_equity": 3, "cash": 9},
        "top_sectors": {"government_bonds": 30, "corporate_bonds": 22, "financials": 8, "technology": 6, "other": 34},
    },

    # ─── RBC Funds ───────────────────────────────────────────────────
    "RBF460": {
        "name": "RBC Canadian Dividend Fund",
        "category": "Canadian Dividend",
        "mer": 1.72,
        "allocation": {"cad_equity": 85, "us_equity": 8, "cash": 7},
        "top_sectors": {"financials": 38, "energy": 14, "utilities": 10, "communication": 8, "industrials": 7, "real_estate": 6, "other": 17},
    },
    "RBF556": {
        "name": "RBC Balanced Fund",
        "category": "Canadian Balanced",
        "mer": 1.79,
        "allocation": {"cad_equity": 30, "us_equity": 15, "cad_bonds": 30, "intl_developed_equity": 10, "global_bonds": 8, "cash": 7},
        "top_sectors": {"financials": 18, "government_bonds": 16, "corporate_bonds": 14, "energy": 8, "technology": 7, "other": 37},
    },
    "RBF559": {
        "name": "RBC Global Equity Fund",
        "category": "Global Equity",
        "mer": 2.05,
        "allocation": {"us_equity": 52, "intl_developed_equity": 28, "emerging_equity": 10, "cad_equity": 5, "cash": 5},
        "top_sectors": {"technology": 26, "healthcare": 14, "financials": 13, "industrials": 11, "consumer_discretionary": 10, "other": 26},
    },
    "RBF270": {
        "name": "RBC Canadian Index Fund",
        "category": "Canadian Equity",
        "mer": 0.66,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 33, "energy": 17, "materials": 11, "industrials": 10, "technology": 8, "other": 21},
    },
    "RBF557": {
        "name": "RBC Select Balanced Portfolio",
        "category": "Balanced",
        "mer": 1.85,
        "allocation": {"cad_equity": 22, "us_equity": 18, "cad_bonds": 28, "intl_developed_equity": 12, "global_bonds": 12, "cash": 8},
        "top_sectors": {"government_bonds": 18, "financials": 16, "corporate_bonds": 14, "technology": 10, "other": 42},
    },
    "RBF558": {
        "name": "RBC Select Growth Portfolio",
        "category": "Growth",
        "mer": 1.85,
        "allocation": {"us_equity": 28, "cad_equity": 25, "intl_developed_equity": 18, "emerging_equity": 5, "cad_bonds": 12, "global_bonds": 7, "cash": 5},
        "top_sectors": {"technology": 18, "financials": 16, "industrials": 9, "healthcare": 8, "government_bonds": 8, "other": 41},
    },

    # ─── BMO Funds & ETFs ────────────────────────────────────────────
    "ZSP": {
        "name": "BMO S&P 500 Index ETF",
        "category": "US Equity ETF",
        "mer": 0.09,
        "allocation": {"us_equity": 100},
        "top_sectors": {"technology": 32, "healthcare": 12, "financials": 12, "consumer_discretionary": 10, "communication": 9, "industrials": 8, "other": 17},
    },
    "ZCN": {
        "name": "BMO S&P/TSX Capped Composite ETF",
        "category": "Canadian Equity ETF",
        "mer": 0.06,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 33, "energy": 17, "materials": 11, "industrials": 10, "technology": 8, "other": 21},
    },
    "ZEA": {
        "name": "BMO MSCI EAFE Index ETF",
        "category": "International Equity ETF",
        "mer": 0.22,
        "allocation": {"intl_developed_equity": 100},
        "top_sectors": {"financials": 18, "industrials": 15, "healthcare": 12, "consumer_discretionary": 11, "technology": 10, "other": 34},
    },
    "ZEM": {
        "name": "BMO MSCI Emerging Markets ETF",
        "category": "Emerging Markets ETF",
        "mer": 0.28,
        "allocation": {"emerging_equity": 100},
        "top_sectors": {"technology": 22, "financials": 20, "consumer_discretionary": 14, "communication": 10, "materials": 8, "other": 26},
    },
    "ZGRO": {
        "name": "BMO Growth ETF",
        "category": "Global Growth ETF",
        "mer": 0.20,
        "allocation": {"us_equity": 35, "cad_equity": 20, "intl_developed_equity": 15, "emerging_equity": 7, "cad_bonds": 12, "global_bonds": 6, "cash": 5},
        "top_sectors": {"technology": 17, "financials": 15, "government_bonds": 9, "industrials": 8, "other": 51},
    },
    "ZBAL": {
        "name": "BMO Balanced ETF",
        "category": "Global Balanced ETF",
        "mer": 0.20,
        "allocation": {"us_equity": 22, "cad_equity": 15, "cad_bonds": 28, "intl_developed_equity": 10, "global_bonds": 12, "emerging_equity": 5, "cash": 8},
        "top_sectors": {"government_bonds": 20, "corporate_bonds": 15, "financials": 12, "technology": 10, "other": 43},
    },
    "ZDV": {
        "name": "BMO Canadian Dividend ETF",
        "category": "Canadian Dividend ETF",
        "mer": 0.39,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 40, "energy": 18, "utilities": 10, "communication": 8, "real_estate": 6, "other": 18},
    },
    "ZWB": {
        "name": "BMO Covered Call Canadian Banks ETF",
        "category": "Canadian Financials ETF",
        "mer": 0.72,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 100},
    },

    # ─── TD e-Series ─────────────────────────────────────────────────
    "TDB909": {
        "name": "TD International Index Fund",
        "category": "International Equity",
        "mer": 0.50,
        "allocation": {"intl_developed_equity": 100},
        "top_sectors": {"financials": 18, "industrials": 15, "healthcare": 12, "consumer_discretionary": 11, "technology": 10, "other": 34},
    },
    "TDB613": {
        "name": "TD Balanced Growth Fund",
        "category": "Balanced",
        "mer": 2.07,
        "allocation": {"cad_equity": 25, "us_equity": 20, "cad_bonds": 25, "intl_developed_equity": 12, "global_bonds": 10, "cash": 8},
        "top_sectors": {"financials": 16, "government_bonds": 15, "corporate_bonds": 12, "technology": 10, "energy": 7, "other": 40},
    },
    "TDB622": {
        "name": "TD Dividend Growth Fund",
        "category": "Canadian Dividend",
        "mer": 1.93,
        "allocation": {"cad_equity": 80, "us_equity": 12, "cash": 8},
        "top_sectors": {"financials": 35, "energy": 14, "utilities": 10, "industrials": 9, "communication": 8, "other": 24},
    },

    # ─── CIBC Funds ──────────────────────────────────────────────────
    "CIB225": {
        "name": "CIBC Balanced Fund",
        "category": "Canadian Balanced",
        "mer": 2.12,
        "allocation": {"cad_equity": 28, "us_equity": 15, "cad_bonds": 30, "intl_developed_equity": 10, "global_bonds": 10, "cash": 7},
        "top_sectors": {"government_bonds": 18, "financials": 16, "corporate_bonds": 14, "technology": 8, "energy": 7, "other": 37},
    },
    "CIB520": {
        "name": "CIBC Canadian Equity Fund",
        "category": "Canadian Equity",
        "mer": 2.18,
        "allocation": {"cad_equity": 92, "cash": 8},
        "top_sectors": {"financials": 32, "energy": 16, "materials": 12, "industrials": 10, "technology": 8, "other": 22},
    },
    "CIB456": {
        "name": "Renaissance Global Growth Fund",
        "category": "Global Equity",
        "mer": 2.30,
        "allocation": {"us_equity": 55, "intl_developed_equity": 25, "emerging_equity": 10, "cad_equity": 5, "cash": 5},
        "top_sectors": {"technology": 28, "healthcare": 14, "financials": 12, "consumer_discretionary": 11, "industrials": 10, "other": 25},
    },

    # ─── Manulife Funds ──────────────────────────────────────────────
    "MMF3530": {
        "name": "Manulife Canadian Balanced Fund",
        "category": "Canadian Balanced",
        "mer": 2.22,
        "allocation": {"cad_equity": 32, "us_equity": 12, "cad_bonds": 32, "intl_developed_equity": 8, "global_bonds": 8, "cash": 8},
        "top_sectors": {"financials": 17, "government_bonds": 16, "corporate_bonds": 14, "energy": 8, "industrials": 7, "other": 38},
    },
    "MMF4560": {
        "name": "Manulife Dividend Income Fund",
        "category": "Canadian Dividend",
        "mer": 2.08,
        "allocation": {"cad_equity": 70, "us_equity": 18, "intl_developed_equity": 5, "cash": 7},
        "top_sectors": {"financials": 32, "energy": 14, "utilities": 10, "communication": 8, "industrials": 7, "real_estate": 5, "other": 24},
    },
    "MMF1490": {
        "name": "Manulife Global Equity Fund",
        "category": "Global Equity",
        "mer": 2.35,
        "allocation": {"us_equity": 55, "intl_developed_equity": 22, "emerging_equity": 12, "cad_equity": 5, "cash": 6},
        "top_sectors": {"technology": 26, "healthcare": 14, "financials": 13, "consumer_discretionary": 11, "industrials": 10, "other": 26},
    },

    # ─── Desjardins Funds ────────────────────────────────────────────
    "DJT510": {
        "name": "Desjardins Canadian Equity Fund",
        "category": "Canadian Equity",
        "mer": 2.15,
        "allocation": {"cad_equity": 90, "us_equity": 5, "cash": 5},
        "top_sectors": {"financials": 30, "energy": 16, "materials": 12, "industrials": 10, "technology": 8, "other": 24},
    },
    "DJT710": {
        "name": "Desjardins Global Equity Fund",
        "category": "Global Equity",
        "mer": 2.28,
        "allocation": {"us_equity": 50, "intl_developed_equity": 25, "emerging_equity": 10, "cad_equity": 8, "cash": 7},
        "top_sectors": {"technology": 25, "healthcare": 14, "financials": 13, "industrials": 11, "consumer_discretionary": 10, "other": 27},
    },
    "DJT300": {
        "name": "Desjardins Balanced Fund",
        "category": "Canadian Balanced",
        "mer": 2.10,
        "allocation": {"cad_equity": 28, "us_equity": 14, "cad_bonds": 32, "intl_developed_equity": 8, "global_bonds": 10, "cash": 8},
        "top_sectors": {"government_bonds": 18, "financials": 16, "corporate_bonds": 14, "energy": 7, "technology": 7, "other": 38},
    },

    # ─── More Popular ETFs ───────────────────────────────────────────
    "VCN": {
        "name": "Vanguard FTSE Canada All Cap",
        "category": "Canadian Equity ETF",
        "mer": 0.05,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 34, "energy": 16, "materials": 11, "industrials": 10, "technology": 8, "other": 21},
    },
    "VUN": {
        "name": "Vanguard U.S. Total Market Index ETF",
        "category": "US Equity ETF",
        "mer": 0.16,
        "allocation": {"us_equity": 100},
        "top_sectors": {"technology": 31, "healthcare": 12, "financials": 12, "consumer_discretionary": 11, "industrials": 9, "other": 25},
    },
    "VIU": {
        "name": "Vanguard FTSE Dev All Cap ex NA",
        "category": "International Equity ETF",
        "mer": 0.22,
        "allocation": {"intl_developed_equity": 100},
        "top_sectors": {"financials": 18, "industrials": 15, "healthcare": 12, "consumer_discretionary": 11, "technology": 10, "other": 34},
    },
    "VEE": {
        "name": "Vanguard FTSE Emerging Markets",
        "category": "Emerging Markets ETF",
        "mer": 0.24,
        "allocation": {"emerging_equity": 100},
        "top_sectors": {"technology": 22, "financials": 20, "consumer_discretionary": 14, "communication": 10, "materials": 8, "other": 26},
    },
    "VBAL": {
        "name": "Vanguard Balanced ETF Portfolio",
        "category": "Global Balanced ETF",
        "mer": 0.24,
        "allocation": {"us_equity": 22, "cad_equity": 14, "cad_bonds": 22, "intl_developed_equity": 10, "global_bonds": 16, "emerging_equity": 4, "us_bonds": 6, "cash": 6},
        "top_sectors": {"government_bonds": 20, "corporate_bonds": 15, "financials": 12, "technology": 10, "other": 43},
    },
    "VCNS": {
        "name": "Vanguard Conservative ETF Portfolio",
        "category": "Global Conservative ETF",
        "mer": 0.24,
        "allocation": {"cad_bonds": 30, "global_bonds": 20, "us_equity": 14, "cad_equity": 8, "us_bonds": 10, "intl_developed_equity": 6, "emerging_equity": 3, "cash": 9},
        "top_sectors": {"government_bonds": 28, "corporate_bonds": 18, "financials": 8, "technology": 6, "other": 40},
    },
    "XBAL": {
        "name": "iShares Core Balanced ETF Portfolio",
        "category": "Global Balanced ETF",
        "mer": 0.20,
        "allocation": {"us_equity": 22, "cad_equity": 14, "cad_bonds": 28, "intl_developed_equity": 10, "global_bonds": 12, "emerging_equity": 4, "cash": 10},
        "top_sectors": {"government_bonds": 20, "corporate_bonds": 16, "financials": 12, "technology": 10, "other": 42},
    },
    "QQC": {
        "name": "Invesco NASDAQ 100 Index ETF (CAD)",
        "category": "US Tech ETF",
        "mer": 0.39,
        "allocation": {"us_equity": 100},
        "top_sectors": {"technology": 52, "consumer_discretionary": 15, "communication": 14, "healthcare": 7, "consumer_staples": 4, "other": 8},
    },
    "HXS": {
        "name": "Global X S&P 500 Index ETF",
        "category": "US Equity ETF",
        "mer": 0.10,
        "allocation": {"us_equity": 100},
        "top_sectors": {"technology": 32, "healthcare": 12, "financials": 12, "consumer_discretionary": 10, "communication": 9, "industrials": 8, "other": 17},
    },
    "HXT": {
        "name": "Global X S&P/TSX 60 Index ETF",
        "category": "Canadian Equity ETF",
        "mer": 0.03,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 35, "energy": 16, "materials": 10, "industrials": 9, "technology": 8, "other": 22},
    },
    "XSP": {
        "name": "iShares Core S&P 500 (CAD-Hedged)",
        "category": "US Equity ETF (Hedged)",
        "mer": 0.10,
        "allocation": {"us_equity": 100},
        "top_sectors": {"technology": 32, "healthcare": 12, "financials": 12, "consumer_discretionary": 10, "communication": 9, "industrials": 8, "other": 17},
    },
    "XQQ": {
        "name": "iShares NASDAQ 100 (CAD-Hedged)",
        "category": "US Tech ETF (Hedged)",
        "mer": 0.39,
        "allocation": {"us_equity": 100},
        "top_sectors": {"technology": 52, "consumer_discretionary": 15, "communication": 14, "healthcare": 7, "consumer_staples": 4, "other": 8},
    },
    "ZEB": {
        "name": "BMO Equal Weight Banks ETF",
        "category": "Canadian Banks ETF",
        "mer": 0.28,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 100},
    },
    "ZRE": {
        "name": "BMO Equal Weight REITs ETF",
        "category": "Canadian REIT ETF",
        "mer": 0.61,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"real_estate": 100},
    },
    "XRE": {
        "name": "iShares S&P/TSX Capped REIT",
        "category": "Canadian REIT ETF",
        "mer": 0.61,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"real_estate": 100},
    },
    "ZWC": {
        "name": "BMO Canadian High Dividend Covered Call",
        "category": "Canadian Dividend ETF",
        "mer": 0.72,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 35, "energy": 18, "utilities": 12, "communication": 8, "real_estate": 6, "other": 21},
    },
    "HDIV": {
        "name": "Hamilton Enhanced Multi-Sector Covered Call",
        "category": "Canadian Covered Call ETF",
        "mer": 0.65,
        "allocation": {"cad_equity": 40, "us_equity": 35, "intl_developed_equity": 15, "cash": 10},
        "top_sectors": {"financials": 30, "utilities": 15, "energy": 12, "technology": 10, "real_estate": 8, "other": 25},
    },
    "HMAX": {
        "name": "Hamilton Canadian Financials Yield Maximizer",
        "category": "Canadian Banks ETF",
        "mer": 0.65,
        "allocation": {"cad_equity": 100},
        "top_sectors": {"financials": 100},
    },

    # ─── GICs & Money Market (for completeness) ─────────────────────
    "DYN029": {
        "name": "Dynamic Money Market Fund",
        "category": "Money Market",
        "mer": 0.85,
        "allocation": {"cash": 100},
        "top_sectors": {"other": 100},
    },
    "PSA": {
        "name": "Purpose High Interest Savings ETF",
        "category": "Cash / HISA ETF",
        "mer": 0.16,
        "allocation": {"cash": 100},
        "top_sectors": {"other": 100},
    },
    "CASH": {
        "name": "Global X High Interest Savings ETF",
        "category": "Cash / HISA ETF",
        "mer": 0.16,
        "allocation": {"cash": 100},
        "top_sectors": {"other": 100},
    },
}

REGION_LABELS = {
    "us_equity": "US Equity",
    "cad_equity": "Canadian Equity",
    "intl_developed_equity": "Intl Developed",
    "emerging_equity": "Emerging Markets",
    "cad_bonds": "Canadian Bonds",
    "global_bonds": "Global Bonds",
    "us_bonds": "US Bonds",
    "cash": "Cash & Equiv.",
}

REGION_COLORS = {
    "us_equity": "#3b82f6",
    "cad_equity": "#ef4444",
    "intl_developed_equity": "#a855f7",
    "emerging_equity": "#f59e0b",
    "cad_bonds": "#22c55e",
    "global_bonds": "#06b6d4",
    "us_bonds": "#6366f1",
    "cash": "#94a3b8",
}

SECTOR_LABELS = {
    "technology": "Technology",
    "financials": "Financials",
    "healthcare": "Healthcare",
    "industrials": "Industrials",
    "consumer_discretionary": "Consumer Disc.",
    "consumer_staples": "Consumer Staples",
    "energy": "Energy",
    "materials": "Materials",
    "communication": "Communication",
    "utilities": "Utilities",
    "real_estate": "Real Estate",
    "government_bonds": "Gov. Bonds",
    "corporate_bonds": "Corp. Bonds",
    "mortgage_backed": "Mortgage-Backed",
    "other": "Other",
}


def lookup_fund(code: str) -> dict | None:
    key = code.upper().strip()
    return FUND_DATABASE.get(key)


def search_funds(query: str) -> list[dict]:
    q = query.lower().strip()
    results = []
    for code, data in FUND_DATABASE.items():
        if q in code.lower() or q in data["name"].lower() or q in data.get("category", "").lower():
            results.append({"code": code, **data})
    return results[:20]
